[package]
name = "long-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
long-ast = { path = "../ast" }
long-sourceloc = { path = "../sourceloc" }
anyhow = "= 1.0.45"

[dev-dependencies]
insta = "= 1.7.1"
