[package]
name = "long-lower"
version = "0.1.0"
edition = "2021"

[dependencies]
long-ast = { path = "../ast" }
long-ir = { path = "../ir" }

[dev-dependencies]
insta = "= 1.7.1"
long-parser = { path = "../parser" }
